{{- if empty .Values.geoserver.secret.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: geoserver-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # geoserver admin credentials
  GEOSERVER_ADMIN_USER: {{ .Values.geoserver.secret.admin_username | b64enc }}
  GEOSERVER_ADMIN_PASSWORD: {{ .Values.geoserver.secret.admin_password | b64enc }}

  # geonode oauth2
  OAUTH2_API_KEY: ""
  OAUTH2_CLIENT_ID: {{ .Values.geonode.secret.oauth2.clientId | b64enc}}
  OAUTH2_CLIENT_SECRET: {{ .Values.geonode.secret.oauth2.clientSecret | b64enc }}
{{ end }}