{{ if .Values.pycsw.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pycsw-mappings-py
  namespace: {{ .Release.Namespace }}
data:
  pycsw-mappings.py: |
    # copied from 4.1.x: https://github.com/GeoNode/geonode/blob/master/geonode/catalogue/backends/pycsw_local_mappings.py
    MD_CORE_MODEL = {
      "typename": "pycsw:CoreMetadata",
      "outputschema": "http://pycsw.org/metadata",
      "mappings": {
          "pycsw:Identifier": "uuid",
          "pycsw:Typename": "csw_typename",
          "pycsw:Schema": "csw_schema",
          "pycsw:MdSource": "csw_mdsource",
          "pycsw:InsertDate": "csw_insert_date",
          "pycsw:XML": "metadata_xml",
          "pycsw:AnyText": "csw_anytext",
          "pycsw:Language": "language",
          "pycsw:Title": "title",
          "pycsw:Abstract": "raw_abstract",
          "pycsw:Keywords": "keyword_csv",
          "pycsw:KeywordType": "keywordstype",
          "pycsw:Format": "spatial_representation_type_string",
          "pycsw:Source": "source",
          "pycsw:Date": "date",
          "pycsw:Modified": "date",
          "pycsw:Type": "csw_type",
          "pycsw:BoundingBox": "csw_wkt_geometry",
          "pycsw:CRS": "csw_crs",
          "pycsw:AlternateTitle": "alternate",
          "pycsw:RevisionDate": "date",
          "pycsw:CreationDate": "date",
          "pycsw:PublicationDate": "date",
          "pycsw:Organization": "organizationname",
          "pycsw:OrganizationName": "organizationname",
          "pycsw:SecurityConstraints": "securityconstraints",
          "pycsw:ParentIdentifier": "parentidentifier",
          "pycsw:TopicCategory": "topiccategory",
          "pycsw:ResourceLanguage": "language",
          "pycsw:GeographicDescriptionCode": "geodescode",
          "pycsw:Denominator": "denominator",
          "pycsw:DistanceValue": "distancevalue",
          "pycsw:DistanceUOM": "distanceuom",
          "pycsw:TempExtent_begin": "temporal_extent_start",
          "pycsw:TempExtent_end": "temporal_extent_end",
          "pycsw:ServiceType": "servicetype",
          "pycsw:ServiceTypeVersion": "servicetypeversion",
          "pycsw:Operation": "operation",
          "pycsw:CouplingType": "couplingtype",
          "pycsw:OperatesOn": "operateson",
          "pycsw:OperatesOnIdentifier": "operatesonidentifier",
          "pycsw:OperatesOnName": "operatesoname",
          "pycsw:Degree": "degree",
          "pycsw:AccessConstraints": "restriction_code",
          "pycsw:OtherConstraints": "raw_constraints_other",
          "pycsw:Classification": "classification",
          "pycsw:ConditionApplyingToAccessAndUse": "conditionapplyingtoaccessanduse",
          "pycsw:Lineage": "lineage",
          "pycsw:ResponsiblePartyRole": "responsiblepartyrole",
          "pycsw:SpecificationTitle": "specificationtitle",
          "pycsw:SpecificationDate": "specificationdate",
          "pycsw:SpecificationDateType": "specificationdatetype",
          "pycsw:Creator": "creator",
          "pycsw:Publisher": "publisher",
          "pycsw:Contributor": "contributor",
          "pycsw:Relation": "relation",
          "pycsw:Links": "download_links",
      },
    }
{{ end }}