apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-geonode-uwsgi-ini
data:
  uwsgi.ini: |
    [uwsgi]
    uwsgi-socket = 0.0.0.0:8000
    http-socket = 0.0.0.0:8001
    # pidfile = /tmp/geonode.pid

    chdir = /usr/src/geonode/
    module = geonode.wsgi:application

    strict = false
    master = true
    enable-threads = true
    vacuum = true                        ; Delete sockets during shutdown
    single-interpreter = true
    die-on-term = true                   ; Shutdown when receiving SIGTERM (default is respawn)
    need-app = true

    # logging
    # path to where uwsgi logs will be saved
    logto = /var/log/geonode.log

    touch-reload = /usr/src/geonode/geonode/wsgi.py
    buffer-size = {{ .Values.geonode.uwsgi.buffer_size }}

    harakiri = {{ .Values.geonode.uwsgi.harakiri }}
    py-callos-afterfork = true

    max-requests = {{ .Values.geonode.uwsgi.max_requests }}
    max-worker-lifetime = {{ .Values.geonode.uwsgi.max_worker_lifetime }}
    reload-on-rss = {{ .Values.geonode.uwsgi.reload_on_rss }}
    worker-reload-mercy = {{ .Values.geonode.uwsgi.worker_reload_mercy }}

    cheaper-algo = busyness
    processes = {{ .Values.geonode.uwsgi.processes }}
    cheaper = {{ .Values.geonode.uwsgi.cheaper }}
    cheaper-initial = {{ .Values.geonode.uwsgi.cheaper_initial }}
    cheaper-overload = {{ .Values.geonode.uwsgi.cheaper_overload }}
    cheaper-step = {{ .Values.geonode.uwsgi.cheaper_step }}

    cheaper-busyness-multiplier = {{ .Values.geonode.uwsgi.cheaper_busyness_multiplier }}
    cheaper-busyness-min = {{ .Values.geonode.uwsgi.cheaper_busyness_min }}
    cheaper-busyness-max = {{ .Values.geonode.uwsgi.cheaper_busyness_max }}
    cheaper-busyness-backlog-alert = {{ .Values.geonode.uwsgi.cheaper_busyness_backlog_alert }}
    cheaper-busyness-backlog-step = {{ .Values.geonode.uwsgi.cheaper_busyness_backlog_step }}

    # daemonize = /var/log/uwsgi/geonode.log
    # cron = -1 -1 -1 -1 -1 /usr/local/bin/python /usr/src/geonode/manage.py collect_metrics -n
