apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
data:
  DJANGO_EMAIL_HOST_PASSWORD: {{ .Values.smtp.password | b64enc }}
  ADMIN_PASSWORD: {{ .Values.general.superUser.password | b64enc }}
  GEOSERVER_ADMIN_PASSWORD: {{ b64enc "geoserver" }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc }}
  GEONODE_DATABASE_PASSWORD: {{ .Values.postgresql.password | b64enc }}
  GEONODE_GEODATABASE_PASSWORD: {{ .Values.postgresql.password | b64enc }}
  BROKER_URL: {{ include "broker_url" . | b64enc }}
  DATABASE_URL: {{ include "database_geonode" . | b64enc }}
  GEODATABASE_URL: {{ include "database_geonode_data" . | b64enc }}
  {{- range $key, $val := .Values.geonode.extraSecretEnvs }}
  {{ $key  }}: {{ b64enc $val }}
  {{- end }}
